services:
  - type: web
    name: viraler-ia
    env: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: FFMPEG_PATH
        value: /usr/bin/ffmpeg
    disk:
      name: data
      mountPath: /opt/data
      sizeGB: 1
