// Plantillas pre-armadas con estética "Algo Sentido": elegante, no distractora, calidad editorial.
// Pensadas para que el espectador perciba madurez/oficio en vez de la energía Opus Clip / TikTok.
// Cada plantilla setea ~22 params del editor en un click.

// Paleta de referencia (warm, muted, editorial):
//   Crema:     #F5F1E8
//   Off-white: #FAFAF7
//   Arena:     #E8E4D8
//   Oro envejecido: #C9A961
//   Oro metálico:   #D4AF37
//   Terracota: #94553A
//   Sage:      #8FA686
//   Carbón:    #1F1F1F

export const CAPTION_TEMPLATES = [
  {
    id: 'editorial',
    name: 'Editorial',
    description: 'Revista impresa: Lora serif cálida + Playfair italic en keywords + crema + oro envejecido. Elegancia atemporal.',
    swatch: { bg: '#1F1F1F', text: '#F5F1E8', accent: '#C9A961' },
    params: {
      font_hook: 'PlayfairDisplay',
      font_caption: 'LoraSemiBold',
      font_keyword: 'PlayfairDisplayItalic',
      hook_color: '#F5F1E8',
      caption_color: '#FAFAF7',
      keyword_color: '#C9A961',
      keyword_bg_color: '',
      keyword_bg_opacity: 100,
      outline_enabled: 1,
      outline_color: '#000000',
      outline_thickness: 2,
      shadow_opacity: 35,
      hook_font_size: 78,
      caption_font_size: 54,
      hook_italic: 0, hook_underline: 0,
      caption_italic: 0, caption_underline: 0,
      keyword_italic: 0, keyword_underline: 0,
    },
  },
  {
    id: 'documentary',
    name: 'Documentary',
    description: 'TED / docu Netflix: Inter limpio, blanco puro, contorno mínimo. Funcional, neutro, profesional.',
    swatch: { bg: '#0F0F12', text: '#FFFFFF', accent: '#FFFFFF' },
    params: {
      font_hook: 'InterBold',
      font_caption: 'InterMedium',
      font_keyword: 'InterBold',
      hook_color: '#FFFFFF',
      caption_color: '#FFFFFF',
      keyword_color: '#FFFFFF',
      keyword_bg_color: '',
      keyword_bg_opacity: 100,
      outline_enabled: 1,
      outline_color: '#000000',
      outline_thickness: 2,
      shadow_opacity: 60,
      hook_font_size: 72,
      caption_font_size: 50,
      hook_italic: 0, hook_underline: 0,
      caption_italic: 0, caption_underline: 0,
      keyword_italic: 0, keyword_underline: 0,
    },
  },
  {
    id: 'boutique',
    name: 'Boutique',
    description: 'Lujo discreto: Lato cálido + DM Serif italic + crema sobre crema + oro metálico sutil.',
    swatch: { bg: '#1A1410', text: '#F5F1E8', accent: '#D4AF37' },
    params: {
      font_hook: 'LatoBold',
      font_caption: 'LatoBold',
      font_keyword: 'DMSerifDisplayItalic',
      hook_color: '#F5F1E8',
      caption_color: '#E8E4D8',
      keyword_color: '#D4AF37',
      keyword_bg_color: '',
      keyword_bg_opacity: 100,
      outline_enabled: 1,
      outline_color: '#000000',
      outline_thickness: 2,
      shadow_opacity: 45,
      hook_font_size: 70,
      caption_font_size: 48,
      hook_italic: 0, hook_underline: 0,
      caption_italic: 0, caption_underline: 0,
      keyword_italic: 0, keyword_underline: 0,
    },
  },
  {
    id: 'whisper',
    name: 'Whisper',
    description: 'Susurro reflexivo: Inter Regular fino, tamaño chico, sin contorno, solo sombra. Para podcasts y reflexión.',
    swatch: { bg: '#15161A', text: '#F5F1E8', accent: '#FFFFFF' },
    params: {
      font_hook: 'InterMedium',
      font_caption: 'InterRegular',
      font_keyword: 'InterMedium',
      hook_color: '#F5F1E8',
      caption_color: '#F5F1E8',
      keyword_color: '#FFFFFF',
      keyword_bg_color: '',
      keyword_bg_opacity: 100,
      outline_enabled: 0,
      outline_color: '#000000',
      outline_thickness: 0,
      shadow_opacity: 75,
      hook_font_size: 56,
      caption_font_size: 40,
      hook_italic: 0, hook_underline: 0,
      caption_italic: 0, caption_underline: 0,
      keyword_italic: 0, keyword_underline: 0,
    },
  },
  {
    id: 'manuscrito',
    name: 'Manuscrito',
    description: 'Casual con clase: EB Garamond + Caveat manuscrita + terracota. Para contenido personal.',
    swatch: { bg: '#1A1410', text: '#F5F1E8', accent: '#94553A' },
    params: {
      font_hook: 'EBGaramondBold',
      font_caption: 'EBGaramondSemiBold',
      font_keyword: 'CaveatBold',
      hook_color: '#F5F1E8',
      caption_color: '#FAFAF7',
      keyword_color: '#94553A',
      keyword_bg_color: '',
      keyword_bg_opacity: 100,
      outline_enabled: 1,
      outline_color: '#000000',
      outline_thickness: 2,
      shadow_opacity: 40,
      hook_font_size: 68,
      caption_font_size: 50,
      hook_italic: 0, hook_underline: 0,
      caption_italic: 0, caption_underline: 0,
      keyword_italic: 0, keyword_underline: 0,
    },
  },
];
